// topic-15 unified-toast-notification: 全仓业务错误码枚举(34 unique keys)。
// 范围:main 端 object-literal `code: 'X'`(MAIN_ERROR_CODES, 27 keys)+ fs/** `fsError('FS_X', ...)` / `mapNodeErrnoCode()` 返回(FS_ERROR_CODES, 7 keys)。
// 不含:IPC_ERR.*(infra-level, 已是常量见 ipc-result.ts)、plugin user code、third-party error.code。

export const MAIN_ERROR_CODES = {
  AGENT_NOT_AUTHORIZED: 'AGENT_NOT_AUTHORIZED',
  BAD_INPUT: 'BAD_INPUT',
  BAD_MAIN: 'BAD_MAIN',
  BAD_MANIFEST: 'BAD_MANIFEST',
  BAD_ROOT: 'BAD_ROOT',
  BAD_URL: 'BAD_URL',
  BUFFER_SESSION_NOT_FOUND: 'BUFFER_SESSION_NOT_FOUND',
  EEXIST: 'EEXIST',
  GIT_FAILED: 'GIT_FAILED',
  GIT_SPAWN_FAILED: 'GIT_SPAWN_FAILED',
  INVALID_ID: 'INVALID_ID',
  MCP_HOST_BIND_FORBIDDEN: 'MCP_HOST_BIND_FORBIDDEN',
  NO_WINDOW: 'NO_WINDOW',
  NO_WINDOW_SEQ: 'NO_WINDOW_SEQ',
  NOT_INSTALLED: 'NOT_INSTALLED',
  PAYLOAD_TOO_LARGE: 'PAYLOAD_TOO_LARGE',
  POPOUT_NOT_IMPLEMENTED: 'POPOUT_NOT_IMPLEMENTED',
  RM_FAILED: 'RM_FAILED',
  TERMINAL_CWD_UNRESOLVED: 'TERMINAL_CWD_UNRESOLVED',
  TERMINAL_FORBIDDEN_SHELL: 'TERMINAL_FORBIDDEN_SHELL',
  TERMINAL_NO_WINDOW: 'TERMINAL_NO_WINDOW',
  TERMINAL_NOT_FOUND: 'TERMINAL_NOT_FOUND',
  TERMINAL_SESSION_DUPLICATE: 'TERMINAL_SESSION_DUPLICATE',
  TERMINAL_SESSION_NOT_FOUND: 'TERMINAL_SESSION_NOT_FOUND',
  WORKSPACE_NOT_ABSOLUTE: 'WORKSPACE_NOT_ABSOLUTE',
  WORKSPACE_NOT_DIRECTORY: 'WORKSPACE_NOT_DIRECTORY',
  WORKSPACE_NOT_FOUND: 'WORKSPACE_NOT_FOUND',
} as const;

export const FS_ERROR_CODES = {
  FS_BAD_NAME: 'FS_BAD_NAME',
  FS_DENIED: 'FS_DENIED',
  FS_EEXIST: 'FS_EEXIST',
  FS_IO: 'FS_IO',
  FS_NOT_DIRECTORY: 'FS_NOT_DIRECTORY',
  FS_NOT_FILE: 'FS_NOT_FILE',
  FS_NOT_FOUND: 'FS_NOT_FOUND',
} as const;

export const ERROR_CODES = {
  ...MAIN_ERROR_CODES,
  ...FS_ERROR_CODES,
} as const;

export type MainErrorCode = (typeof MAIN_ERROR_CODES)[keyof typeof MAIN_ERROR_CODES];
export type FsErrorCode = (typeof FS_ERROR_CODES)[keyof typeof FS_ERROR_CODES];
export type ErrorCode = (typeof ERROR_CODES)[keyof typeof ERROR_CODES];
