// topic-15 unified-toast-notification: 全仓业务错误码枚举(45 unique keys)。
// 范围:main 端 object-literal `code: 'X'`(MAIN_ERROR_CODES, 36 keys)+ fs/** `fsError('FS_X', ...)` / `mapNodeErrnoCode()` 返回(FS_ERROR_CODES, 9 keys)。
// 不含:IPC_ERR.*(infra-level, 已是常量见 ipc-result.ts)、plugin user code、third-party error.code。

export const MAIN_ERROR_CODES = {
  AGENT_NOT_AUTHORIZED: 'AGENT_NOT_AUTHORIZED',
  AWAIT_STOP_HOOK_ALREADY_PENDING: 'AWAIT_STOP_HOOK_ALREADY_PENDING',
  BAD_INPUT: 'BAD_INPUT',
  BAD_MAIN: 'BAD_MAIN',
  BAD_MANIFEST: 'BAD_MANIFEST',
  BAD_ROOT: 'BAD_ROOT',
  BAD_URL: 'BAD_URL',
  DEBUG_ADAPTER_LAUNCH_FAILED: 'DEBUG_ADAPTER_LAUNCH_FAILED',
  DEBUG_NOT_AUTHORIZED: 'DEBUG_NOT_AUTHORIZED',
  DEBUG_PROGRAM_OUTSIDE_WORKSPACE: 'DEBUG_PROGRAM_OUTSIDE_WORKSPACE',
  DEBUG_RESULT_TOO_LARGE: 'DEBUG_RESULT_TOO_LARGE',
  DEBUG_SESSION_NOT_FOUND: 'DEBUG_SESSION_NOT_FOUND',
  DEBUG_WAIT_TIMEOUT: 'DEBUG_WAIT_TIMEOUT',
  EEXIST: 'EEXIST',
  GIT_FAILED: 'GIT_FAILED',
  GIT_SPAWN_FAILED: 'GIT_SPAWN_FAILED',
  INVALID_ID: 'INVALID_ID',
  MCP_HOST_BIND_FORBIDDEN: 'MCP_HOST_BIND_FORBIDDEN',
  NO_WINDOW: 'NO_WINDOW',
  NO_WINDOW_SEQ: 'NO_WINDOW_SEQ',
  NOT_INSTALLED: 'NOT_INSTALLED',
  PAYLOAD_TOO_LARGE: 'PAYLOAD_TOO_LARGE',
  POPOUT_NOT_IMPLEMENTED: 'POPOUT_NOT_IMPLEMENTED',
  RM_FAILED: 'RM_FAILED',
  TERMINAL_CREATE_CANCELLED: 'TERMINAL_CREATE_CANCELLED',
  TERMINAL_CWD_UNRESOLVED: 'TERMINAL_CWD_UNRESOLVED',
  TERMINAL_FORBIDDEN_SHELL: 'TERMINAL_FORBIDDEN_SHELL',
  TERMINAL_NO_WINDOW: 'TERMINAL_NO_WINDOW',
  TERMINAL_NOT_FOUND: 'TERMINAL_NOT_FOUND',
  TERMINAL_SESSION_DUPLICATE: 'TERMINAL_SESSION_DUPLICATE',
  TERMINAL_SESSION_NOT_FOUND: 'TERMINAL_SESSION_NOT_FOUND',
  // 边界(E235,E230 数量上限族):终端会话(真实 PTY)数超全局/每窗口上限。
  TOO_MANY_TERMINALS: 'TOO_MANY_TERMINALS',
  TERMINAL_WRITE_FAILED: 'TERMINAL_WRITE_FAILED',
  // 边界(E230,E227/E228/E229 数量上限族):并发 active 资源(流式 shell 子进程)超全局/per-sender 上限。
  TOO_MANY_STREAMS: 'TOO_MANY_STREAMS',
  WORKSPACE_NOT_ABSOLUTE: 'WORKSPACE_NOT_ABSOLUTE',
  WORKSPACE_NOT_DIRECTORY: 'WORKSPACE_NOT_DIRECTORY',
  WORKSPACE_NOT_FOUND: 'WORKSPACE_NOT_FOUND',
} as const;

export const FS_ERROR_CODES = {
  FS_BAD_NAME: 'FS_BAD_NAME',
  FS_DENIED: 'FS_DENIED',
  FS_EEXIST: 'FS_EEXIST',
  FS_IO: 'FS_IO',
  FS_NOT_DIRECTORY: 'FS_NOT_DIRECTORY',
  FS_NOT_FILE: 'FS_NOT_FILE',
  FS_NOT_FOUND: 'FS_NOT_FOUND',
  // 边界(E18):readFile 目标超大小上限(防整文件读入内存 + IPC 发送卡死/崩溃)。
  FS_FILE_TOO_LARGE: 'FS_FILE_TOO_LARGE',
  // 边界(E30):目录条目数超硬上限(防超大目录一次性构造数组 + IPC 全量返回卡死)。
  FS_DIR_TOO_LARGE: 'FS_DIR_TOO_LARGE',
} as const;

export const ERROR_CODES = {
  ...MAIN_ERROR_CODES,
  ...FS_ERROR_CODES,
} as const;

export type MainErrorCode = (typeof MAIN_ERROR_CODES)[keyof typeof MAIN_ERROR_CODES];
export type FsErrorCode = (typeof FS_ERROR_CODES)[keyof typeof FS_ERROR_CODES];
export type ErrorCode = (typeof ERROR_CODES)[keyof typeof ERROR_CODES];
